// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CriminalSearchAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250314212734_AddNameAndCaseNumberToCriminal")]
    partial class AddNameAndCaseNumberToCriminal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Criminal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BirthPlace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CrimeLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CrimeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PermanentResidence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonalDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecialFeatures")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tribe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsualPlaces")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Criminals");
                });
#pragma warning restore 612, 618
        }
    }
}
